Purchase Log Update
karthikkumar1996/MedInventory pull request #12
Opened 2020-03-12 09:41 UTC by Kani1996

![image](https://user-images.githubusercontent.com/34624127/76507703-3e739400-6473-11ea-915b-0256f9d6654d.png)
Changes Done :  Added functionality to update the Purchase log

2020-03-12 09:56 UTC, karthikkumar1996 commented
First of all, Thanks for your contribution @Kani1996

2020-03-13 07:57 UTC, KarthikKumarDev requested changes

2020-03-13 07:57 UTC, KarthikKumarDev commented on med-inventory/src/components/purchase-medicine/purchase-layout/PurchaseForm.js
> +    PurchaseNumber: '',
Any reasoning behind this case convention change?

2020-03-13 07:57 UTC, KarthikKumarDev commented on med-inventory/src/components/purchase-medicine/purchase-layout/PurchaseForm.js
> +            Update Log
Can we change this to reflect meaning closer to the Business usecase, rather than DB operation

2020-03-13 09:46 UTC, Kani1996 commented on med-inventory/src/components/purchase-medicine/purchase-layout/PurchaseForm.js
> +    PurchaseNumber: '',
No particular reason... I thought it would be better if the field values matched the table column names.

2020-03-13 09:51 UTC, Kani1996 commented on med-inventory/src/components/purchase-medicine/purchase-layout/PurchaseForm.js
> +            Update Log
Sure... I have updated it to 'handleUpdateLogClick'...

2020-03-13 11:21 UTC, merged